name: MERN Stack Deployment

# This workflow is triggered on every push and can also be manually dispatched.
on:
  push:
  workflow_dispatch:

# Ensures that only one instance of this workflow can run at a time.
concurrency:
  group: ${{ github.workflow }}

jobs:
  
  # First job installs dependencies and checks the runner environment
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
     
  # Deploy to DEV environment on Render
  Deploy_DEV:
    runs-on: ubuntu-latest
    needs: Check
    steps:
      - name: Deploy to DEV environment on Render
        uses: renderapp/cli-action@v1
        with:
          command: render deploy
          args: --env DEV
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
  
  # Manual approval for Production deployment
  Manual_Approval:
    runs-on: ubuntu-latest
    needs: Deploy_DEV
    steps:
      - name: Wait for manual approval
        uses: tzkhan/approval-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
  # Deploy to Production on Render after approval
  Deploy_Prod:
    runs-on: ubuntu-latest
    needs: Manual_Approval
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Deploy to Production on Render
        uses: renderapp/cli-action@v1
        with:
          command: render deploy
          args: --env PROD
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
