name: CI/CD Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - prod

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-to-dev:
    needs: build-and-test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to dev environment..."

  deploy-to-prod:
    needs: build-and-test
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to prod environment..."
        
